services:

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://ms-auth:8080
      LEAGUES_SERVICE_URL: http://ms-leagues:8080
      TEAMS_SERVICE_URL: http://ms-teams:8080
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080
      STANDINGS_SERVICE_URL: http://ms-standings:8080
      NOTIFICATIONS_SERVICE_URL: http://ms-notifications:8080
      DASHBOARD_SERVICE_URL: http://ms-dashboard:8080

  ms-auth:
    build: ./ms-auth
    ports:
      - "8081:8080"
    depends_on:
      - postgres-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET: sportpulse-secret-key-2025
      JWT_EXPIRATION: 3600000

  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"

  ms-leagues:
    build: ./ms-leagues
    ports:
      - "8082:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      JWT_SECRET: sportpulse-secret-key-2025

  ms-teams:
    build: ./ms-teams
    ports:
      - "8083:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      JWT_SECRET: sportpulse-secret-key-2025

  ms-fixtures:
    build: ./ms-fixtures
    ports:
      - "8085:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      JWT_SECRET: sportpulse-secret-key-2025
      TEAMS_SERVICE_URL: http://ms-teams:8080

  ms-standings:
    build: ./ms-standings
    ports:
      - "8086:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      JWT_SECRET: sportpulse-secret-key-2025
      TEAMS_SERVICE_URL: http://ms-teams:8080

  postgres-notifications:
    image: postgres:15
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"

  ms-notifications:
    build: ./ms-notifications
    ports:
      - "8088:8080"
    depends_on:
      - postgres-notifications
      - ms-fixtures
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notifications:5432/notifications_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET: sportpulse-secret-key-2025
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080

  ms-dashboard:
    build: ./ms-dashboard
    ports:
      - "8089:8080"
    depends_on:
      - ms-fixtures
      - ms-standings
      - ms-leagues
    environment:
      JWT_SECRET: sportpulse-secret-key-2025
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080
      STANDINGS_SERVICE_URL: http://ms-standings:8080
      LEAGUES_SERVICE_URL: http://ms-leagues:8080