services:

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://ms-auth:8080
      LEAGUES_SERVICE_URL: http://ms-leagues:8080
      TEAMS_SERVICE_URL: http://ms-teams:8080
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080
      STANDINGS_SERVICE_URL: http://ms-standings:8080
      NOTIFICATIONS_SERVICE_URL: http://ms-notifications:8080
      DASHBOARD_SERVICE_URL: http://ms-dashboard:8080

  ms-auth:
    build: ./ms-auth
    ports:
      - "8081:8080"
    depends_on:
      - postgres-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/${AUTH_DATABASE_NAME:?La base de datos de auth debe estar configurada}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DATABASE_USER:?El usuario de la base de datos de auth debe estar configurado}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DATABASE_PASSWORD:?La contraseña de la base de datos de auth debe estar configurada}
      AUTH_JWT_SECRET_KEY: ${AUTH_JWT_SECRET_KEY:?El secret de JWT debe ser configurado}
      AUTH_JWT_EXPIRATION: ${AUTH_JWT_EXPIRATION:-3600000}

  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: ${AUTH_DATABASE_NAME:?La base de datos de auth debe estar configurada}
      POSTGRES_USER: ${AUTH_DATABASE_USER:?El usuario de la base de datos de auth debe estar configurado}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD:?La contraseña de la base de datos de auth debe estar configurada}
    volumes:
     - ./scripts/auth-schema.sql:/docker-entrypoint-initdb.d/auth.sql:ro
    ports:
      - "5433:5432"

  ms-leagues:
    build: ./ms-leagues
    ports:
      - "8082:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      AUTH_URL: http://ms-auth:8080

  ms-teams:
    build: ./ms-teams
    ports:
      - "8083:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      AUTH_URL: http://ms-auth:8080

  ms-fixtures:
    build: ./ms-fixtures
    ports:
      - "8085:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
      TEAMS_SERVICE_URL: http://ms-teams:8080
      AUTH_URL: http://ms-auth:8080

  ms-standings:
    build: ./ms-standings
    ports:
      - "8086:8080"
    environment:
      FOOTBALL_API_URL: ${FOOTBALL_API_URL:?La api externa debe estar configurada}
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY:?La api externa no puede usarse sin la api key}
      TEAMS_SERVICE_URL: http://ms-teams:8080
      AUTH_URL: http://ms-auth:8080

  postgres-notifications:
    image: postgres:15
    environment:
      POSTGRES_DB: ${NOTIFICATIONS_DATABASE_NAME:?La base de datos de notifications debe estar configurada}
      POSTGRES_USER: ${NOTIFICATIONS_DATABASE_USER:?El usuario de la base de datos de notifications debe estar configurado}
      POSTGRES_PASSWORD: ${NOTIFICATIONS_DATABASE_PASSWORD:?La contraseña de la base de datos de notifications debe estar configurada}
    volumes:
      - ./scripts/notifications-schema.sql:/docker-entrypoint-initdb.d/notifications.sql:ro
    ports:
      - "5434:5432"

  ms-notifications:
    build: ./ms-notifications
    ports:
      - "8088:8080"
    depends_on:
      - postgres-notifications
      - ms-fixtures
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notifications:5432/${NOTIFICATIONS_DATABASE_NAME:?La base de datos de notifications debe estar configurada}
      SPRING_DATASOURCE_USERNAME: ${NOTIFICATIONS_DATABASE_USER:?El usuario de la base de datos de notifications debe estar configurado}
      SPRING_DATASOURCE_PASSWORD: ${NOTIFICATIONS_DATABASE_PASSWORD:?La contraseña de la base de datos de notifications debe estar configurada}
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080
      AUTH_URL: http://ms-auth:8080

  ms-dashboard:
    build: ./ms-dashboard
    ports:
      - "8089:8080"
    depends_on:
      - ms-fixtures
      - ms-standings
      - ms-leagues
    environment:
      FIXTURES_SERVICE_URL: http://ms-fixtures:8080
      STANDINGS_SERVICE_URL: http://ms-standings:8080
      LEAGUES_SERVICE_URL: http://ms-leagues:8080