server:
  port: 8086

teams:
    url: ${TEAMS_URL}
auth:
  url: ${AUTH_URL}
api:
  allowedServices: [MS_DASHBOARD]
  football:
    key: ${FOOTBALL_API_KEY}
    url: ${FOOTBALL_API_URL}
spring:
  application:
    name: ms-standings
  management:
    endpoints:
      web:
        exposure:
          include: healthh

