server:
  port: 8081

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5433/${AUTH_DATABASE_NAME}
    username: ${AUTH_DATABASE_USER}
    password: ${AUTH_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

api:
  allowedServices: ["MS-STANDINGS","MS-FIXTURES", "MS-LEAGUES", "MS-TEAMS", "MS-NOTIFICATIONS", "MS-DASHBOARD"]

jwt:
  secretKey: ${AUTH_JWT_SECRET_KEY}
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health