api:
  allowedServices: ["MS-STANDINGS","MS-FIXTURES", "MS-LEAGUES", "MS-TEAMS", "MS-NOTIFICATIONS", "MS-DASHBOARD"]
  football:
    key: ${FOOTBALL_API_KEY}
    url: ${FOOTBALL_API_URL}
auth:
  url: ${AUTH_URL}
server:
  port: 8083
spring:
  application:
    name: ms-teams
  management:
    endpoints:
      web:
        exposure:
          include: health