api:
  allowedServices: [MS_DASHBOARD]
  football:
    key: ${FOOTBALL_API_KEY}
    url: ${FOOTBALL_API_URL}
jwt:
  secret: ${AUTH_JWT_SECRET_KEY}
auth:
  url: http://localhost:8081
server:
  port: 8083
spring:
  application:
    name: ms-teams
  management:
    endpoints:
      web:
        exposure:
          include: health