api:
  football:
    key: ${FOOTBALL_API_KEY}
    url: ${FOOTBALL_API_URL}
server:
  port: 8083
spring:
  application:
    name: ms-teams
  management:
    endpoints:
      web:
        exposure:
          include: health